artifact_location: file:///C:/Users/Jazz/Documents/GitHub/PoseSketeTrain/runs/mlflow/0
creation_time: 1777978637535
experiment_id: '0'
last_update_time: 1777978637535
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
